### ISSUE TITLE
ERROR!!!

### ISSUE THREAD

**Issue by MrTimonM** [NotMRGH/VertusClaimer#3]
2024-09-28 17:11:47 | INFO     | 35 - A02 | Proxy IP: 103.72.212.113
2024-09-28 17:11:47 | INFO     | 35 - A6_02 | Proxy IP: 202.134.9.154
Traceback (most recent call last):
  File "D:\VertusClaimer-master\main.py", line 13, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "D:\VertusClaimer-master\main.py", line 8, in main
    await process()
  File "D:\VertusClaimer-master\bot\utils\launcher.py", line 98, in process
    await run_tasks(tg_clients=tg_clients)
  File "D:\VertusClaimer-master\bot\utils\launcher.py", line 114, in run_tasks
    await asyncio.gather(*tasks)
  File "D:\VertusClaimer-master\bot\core\claimer.py", line 514, in run_claimer
    await Claimer(tg_client=tg_client, proxy=proxy).run()
  File "D:\VertusClaimer-master\bot\core\claimer.py", line 473, in run
    await self.check_proxy(http_client=http_client)
  File "D:\VertusClaimer-master\bot\core\claimer.py", line 30, in check_proxy
    response = await http_client.get("https://httpbin.org/ip", timeout=aiohttp.ClientTimeout(5))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 605, in _request
    await resp.start(conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client_reqrep.py", line 961, in start
    with self._timer:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000025AD1B33910>
Traceback (most recent call last):

**Comment by NotMRGH** [comment]
fixed
